node:
  - name: networks
    remark: 2c2g即可
    url: https://raw.githubusercontent.com/lmooop/lm/main/network3.sh

  - name: waku
    remark: 2c4g即可
    url: https://raw.githubusercontent.com/lmooop/lm/main/waku.sh

miner:
  - name: demo1
    remark: 我是备注5
    url: ""
