node:
  - name: networks3
    remark: 配置要求低
    url: https://raw.githubusercontent.com/lmooop/lm/main/network3.sh

  - name: waku
    remark: 配置要求低
    url: https://raw.githubusercontent.com/lmooop/lm/main/waku.sh

  - name: titan
    remark: 磁盘分配多分多
    url: https://raw.githubusercontent.com/lmooop/lm/main/titan.sh

  - name: rivalz
    remark: 磁盘分配多分多
    url: https://raw.githubusercontent.com/lmooop/lm/main/rivalz.sh

miner:
  - name: demo1
    remark: 我是备注5
    url: ""
