node:
  - name: lilypad
    remark: 需要GPU
    url: https://raw.githubusercontent.com/lmooop/lm/main/lilypad.sh

  - name: flock
    remark: 4C16G100G
    url: https://raw.githubusercontent.com/lmooop/lm/main/flock.sh

  - name: kuzco
    remark: GPU
    url: https://raw.githubusercontent.com/lmooop/lm/main/kuzco.sh

  - name: networks3
    remark: 配置要求低
    url: https://raw.githubusercontent.com/lmooop/lm/main/network3.sh

  - name: waku
    remark: 配置要求低
    url: https://raw.githubusercontent.com/lmooop/lm/main/waku.sh

  - name: titan
    remark: 磁盘分配多分多
    url: https://raw.githubusercontent.com/lmooop/lm/main/titan.sh

  - name: rivalz
    remark: 磁盘分配多分多
    url: https://raw.githubusercontent.com/lmooop/lm/main/rivalz.sh

miner:
  - name: ore_pool
    remark: 矿池一键挖矿脚本
    url: "http://download.bithunter.store:9999/ore/ore_pool.sh"
